branch-defaults:
  main:
    environment: Howdoi-env
  new:
    environment: Howdoi-env
  new2:
    environment: null
    group_suffix: null
environment-defaults:
  Howdoi-env:
    branch: null
    repository: null
global:
  application_name: howdoi
  branch: null
  default_ec2_keyname: aws-key1
  default_platform: Docker running on 64bit Amazon Linux 2
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
